skydive-agent:
  build: ./skydive-agent/
  ports:
   - "8081"
  privileged: true
  links:
   - skydive-analyzer:analyzer
  volumes:
   - ./etc:/etc/skydive
  entrypoint: /go/bin/skydive_agent

skydive-analyzer:
  build: ./skydive-analyzer/
  ports: 
   - "8082:8082"
  links:
   - elasticsearch:elasticsearch
  volumes:
   - ./etc:/etc/skydive

elasticsearch:
  image: elasticsearch
  ports:
   - "9200:9200"
   - "9300:9300"
  log_driver: "none"

