skydive-agent:
  build: ./skydive-agent/
  ports:
   - "8081"
  privileged: true
  links:
   - skydive-analyzer
  volumes:
   - ./:/skydive
#   cmd: skydive-agent --conf /skydive/skydive.ini

skydive-analyzer:
  build: ./skydive-analyzer/
  ports: 
   - "8082:8082"
  links:
   - elasticsearch
  volumes:
   - ./:/skydive

elasticsearch:
  image: elasticsearch
  ports:
   - "9200:9200"
   - "9300:9300"

