version: '2'
#Version 2 files are supported by Compose 1.6.0+ and require a Docker Engine of version 1.10.0+.

services:
  kibana:
    image: kibana:latest
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
     - 5601:5601
    logging:
      driver: "none"
    networks:
      - back

  elasticsearch:
    image: elasticsearch
    container_name: elasticsearch
    ports:
     - "9200:9200"
     - "9300:9300"
    # Filter Elasticsearch very verbose logs to none output
    logging:
      driver: "none"
    volumes:
      - ./data/esdata:/usr/share/elasticsearch/data
    networks:
      - back

  skydive-agent:
    build: ./skydive-agent/
    depends_on:
      - skydive-analyzer
    ports:
     - "8081:8081"
     - "6345:6345/udp"
    privileged: true
    volumes:
     - ./etc:/etc/skydive
    entrypoint: /go/bin/skydive_agent
    network_mode: "host"

  skydive-analyzer:
    build: ./skydive-analyzer/
    container_name: analyzer
    depends_on:
      - elasticsearch
    ports: 
     - "8082:8082"
     - "8082:8082/udp"
    volumes:
     - ./etc:/etc/skydive
    networks:
      - front
      - back

networks:
  front:
    driver: bridge
  back:
    driver: bridge
